services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

# docker network create pg-network

docker run -itd \
    -e POSTGRES_USER="root" \
    -e POSTGRES_PASSWORD="root" \
    -e POSTGRES_DB="ny_taxi" \
    -e PGDATA="/var/lib/postgresql/data/pgdata" \
    -v $(pwd)/ny_taxi_postgres_data:/var/lib/postgresql/data \
    -u 1000:1000 \
    -p 5432:5432 \
    --network=pg-network \
    --name=pg-database \
postgres

docker run -it --detach \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  --network=pg-network \
  --name=pgadmin4 \
  dpage/pgadmin4


URL="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"
python ingest_data.py \
  --user=root \
  --password=root \
  --host=localhost \
  --port=5435 \
  --database=ny_taxi \
  --table=yellow_taxi_trips \
  --csv_url=$(URL)

docker run -it --network=pg-datagbse \
  taxi_ingest:v002 \
  --user=root \
  --password=root \
  --host=localhost \
  --port=5432 \
  --db=ny_taxi \
  --table_name=yellow_taxi_trips \
  --url=${URL} 