services:
  pgdatabase:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_DB: ny_taxi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root